### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ablondin** [yauml/yauml#6]
When installing on Mac OS (I guess it's the same on other platforms), the script does not work and displays a cryptic message:

     $ yauml --help
      File "/usr/bin/yauml", line 238
        print('%s: %s' % (PROGRAM, e), file=sys.stderr)
                                           ^
    SyntaxError: invalid syntax

This is due to the fact that `python` points toward `python2.7` in my case. The first line of `/usr/bin/yaml` is

    #!/usr/bin/env python

When I change it with

    #!/usr/bin/env python3.4

the problem goes away. I'll create a pull request to solve this.

**Comment by sim590** [comment]
Yes! I've figured that after working on python for a while now. Do you think changing to:
```sh
#!/usr/bin/env python3
```
would suffice? This would then not imply an explicit dependency on version **3.4** but rather on version **3.X** and I think that is what we really want, right?

**Comment by ablondin** [comment]
It's better if the solution is more general. I'm working on a pull request right now and I should upload it very soon. It does not require a specific version of Python 3, but any 3.x will work. It simply displays an error message less cryptic.

**Comment by ablondin** [comment]
I've uploaded a pull request. Please review!

**Comment by sim590** [comment]
Solved in #10.
