### ISSUE TITLE
Adding the <<enumeration>> entities

### ISSUE THREAD

**Issue by ablondin** [yauml/yauml#8]
I'm actually modelling a project in which I have enumeration types. It would be nice to support enumeration types, similarly to interfaces. See http://stackoverflow.com/questions/412944/uml-class-diagram-enum for more details.

**Comment by ablondin** [comment]
Please review.

**Comment by sim590** [comment]
Yes, why not! This is good idea!

**Comment by ablondin** [comment]
There is a PR associated with this issue, if you have time to check it :)

**Comment by sim590** [comment]
After all, PR #9 was abandonned in favor of PR #11 which solved the issue.
